// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLePT3mgb7hYuQ8E5xYRix9sau2UpMWw',
    appId: '1:184718732068:web:c082d244a0b4ea764461b1',
    messagingSenderId: '184718732068',
    projectId: 'temp-data-storage-915a3',
    authDomain: 'temp-data-storage-915a3.firebaseapp.com',
    storageBucket: 'temp-data-storage-915a3.appspot.com',
    measurementId: 'G-4KHT5N7D77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4zQBLtOZzIvhRWLs5q9sXaOS8Sti5fs',
    appId: '1:184718732068:android:b628b7ea2881e5454461b1',
    messagingSenderId: '184718732068',
    projectId: 'temp-data-storage-915a3',
    storageBucket: 'temp-data-storage-915a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0WkxUu0YyY1q7MxU6-BHT3RXVldpa_U',
    appId: '1:184718732068:ios:ec4e09823c00f0864461b1',
    messagingSenderId: '184718732068',
    projectId: 'temp-data-storage-915a3',
    storageBucket: 'temp-data-storage-915a3.appspot.com',
    iosClientId: '184718732068-t5bkq0vuasmpmdghso161q0g0768qkj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileUploadFirestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0WkxUu0YyY1q7MxU6-BHT3RXVldpa_U',
    appId: '1:184718732068:ios:ec4e09823c00f0864461b1',
    messagingSenderId: '184718732068',
    projectId: 'temp-data-storage-915a3',
    storageBucket: 'temp-data-storage-915a3.appspot.com',
    iosClientId: '184718732068-t5bkq0vuasmpmdghso161q0g0768qkj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileUploadFirestorage',
  );
}
